add missing dependency
PowerShell 7.6.0-preview.4
PS C:\Users\kushal> cd C:\code\
PS C:\code> mkdir MyMultiplicationDrills

    Directory: C:\code

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            8/3/2025  4:39 AM                MyMultiplicationDrills

PS C:\code> cd C:\code\MyMultiplicationDrills\
PS C:\code\MyMultiplicationDrills> yarn create vite multiplicationdrill --template vanilla-ts
yarn create v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-vite@7.0.3" with binaries:
      - create-vite
      - cva
│
◇  Scaffolding project in C:\code\MyMultiplicationDrills\multiplicationdrill...
│
└  Done. Now run:

  cd multiplicationdrill
  yarn
  yarn dev

Done in 2.61s.
PS C:\code\MyMultiplicationDrills> cd C:\code\MyMultiplicationDrills\multiplicationdrill\
PS C:\code\MyMultiplicationDrills\multiplicationdrill> git status
fatal: not a git repository (or any of the parent directories): .git
PS C:\code\MyMultiplicationDrills\multiplicationdrill> git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in C:/code/MyMultiplicationDrills/multiplicationdrill/.git/
PS C:\code\MyMultiplicationDrills\multiplicationdrill> ls

    Directory: C:\code\MyMultiplicationDrills\multiplicationdrill

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            8/3/2025  4:40 AM                public
d----            8/3/2025  4:40 AM                src
-a---            8/3/2025  4:40 AM            253 .gitignore
-a---            8/3/2025  4:40 AM            356 index.html
-a---            8/3/2025  4:40 AM            277 package.json
-a---            8/3/2025  4:40 AM            607 tsconfig.json

PS C:\code\MyMultiplicationDrills\multiplicationdrill> code C:\code\MyMultiplicationDrills\multiplicationdrill\
code: The term 'code' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\code\MyMultiplicationDrills\multiplicationdrill> git remote add origin git@github.com:multiplicationdrill/multiplicationdrill.github.io.git
PS C:\code\MyMultiplicationDrills\multiplicationdrill> code C:\code\MyMultiplicationDrills\multiplicationdrill\
code: The term 'code' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\code\MyMultiplicationDrills\multiplicationdrill> Set-Location "C:\code\MyMultiplicationDrills\multiplicationdrill\";  Get-Date -Format "yyyy-MM-dd HH:mm:ss"; yarn;  Get-Date -Format "yyyy-MM-dd HH:mm:ss";
2025-08-03 05:10:19
yarn install v1.22.22
info No lockfile found.
[1/4] Resolving packages...
warning @vitest/coverage-v8 > test-exclude > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @vitest/coverage-v8 > test-exclude > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
warning eslint > @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
warning eslint > @humanwhocodes/config-array > @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
warning eslint > file-entry-cache > flat-cache > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning eslint > file-entry-cache > flat-cache > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 50.36s.
2025-08-03 05:11:10
PS C:\code\MyMultiplicationDrills\multiplicationdrill>
PS C:\code\MyMultiplicationDrills\multiplicationdrill>
PS C:\code\MyMultiplicationDrills\multiplicationdrill>
PS C:\code\MyMultiplicationDrills\multiplicationdrill> Set-Location "C:\code\MyMultiplicationDrills\multiplicationdrill\";  Get-Date -Format "yyyy-MM-dd HH:mm:ss"; yarn;  Get-Date -Format "yyyy-MM-dd HH:mm:ss"; yarn build; Get-Date -Format "yyyy-MM-dd HH:mm:ss";
2025-08-03 05:13:18
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.46s.
2025-08-03 05:13:19
yarn run v1.22.22
$ tsc && vite build
src/app.ts:137:3 - error TS2322: Type 'Timeout' is not assignable to type 'number'.

137   autoUpdateTimer = setInterval(() => {
      ~~~~~~~~~~~~~~~

Found 1 error in src/app.ts:137

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2025-08-03 05:13:25
PS C:\code\MyMultiplicationDrills\multiplicationdrill> Set-Location "C:\code\MyMultiplicationDrills\multiplicationdrill\";  Get-Date -Format "yyyy-MM-dd HH:mm:ss"; yarn;  Get-Date -Format "yyyy-MM-dd HH:mm:ss"; yarn build; Get-Date -Format "yyyy-MM-dd HH:mm:ss";
2025-08-03 05:15:50
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.46s.
2025-08-03 05:15:51
yarn run v1.22.22
$ tsc && vite build
vite v7.0.6 building for production...
✓ 8 modules transformed.
dist/index.html                 3.05 kB │ gzip: 0.87 kB
dist/assets/index-DP3U4Tpo.css  5.38 kB │ gzip: 1.62 kB
dist/assets/index-DuqwcOGr.js   7.47 kB │ gzip: 2.48 kB │ map: 25.34 kB
✓ built in 572ms
Done in 6.07s.
2025-08-03 05:15:57
PS C:\code\MyMultiplicationDrills\multiplicationdrill> Set-Location "C:\code\MyMultiplicationDrills\multiplicationdrill\";  Get-Date -Format "yyyy-MM-dd HH:mm:ss"; yarn;  Get-Date -Format "yyyy-MM-dd HH:mm:ss"; yarn build; Get-Date -Format "yyyy-MM-dd HH:mm:ss"; yarn test; Get-Date -Format "yyyy-MM-dd HH:mm:ss";
2025-08-03 05:16:40
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.49s.
2025-08-03 05:16:41
yarn run v1.22.22
$ tsc && vite build
vite v7.0.6 building for production...
✓ 8 modules transformed.
dist/index.html                 3.05 kB │ gzip: 0.87 kB
dist/assets/index-DP3U4Tpo.css  5.38 kB │ gzip: 1.62 kB
dist/assets/index-DuqwcOGr.js   7.47 kB │ gzip: 2.48 kB │ map: 25.34 kB
✓ built in 445ms
Done in 4.22s.
2025-08-03 05:16:45
yarn run v1.22.22
$ vitest
 MISSING DEPENDENCY  Cannot find dependency 'jsdom'

√ Do you want to install jsdom? ... yes
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 31 new dependencies.
info Direct dependencies
└─ jsdom@26.1.0
info All dependencies
├─ @asamuzakjp/css-color@3.2.0
├─ @csstools/color-helpers@5.0.2
├─ @csstools/css-calc@2.1.4
├─ @csstools/css-color-parser@3.0.10
├─ @csstools/css-parser-algorithms@3.0.5
├─ @csstools/css-tokenizer@3.0.4
├─ agent-base@7.1.4
├─ cssstyle@4.6.0
├─ data-urls@5.0.0
├─ decimal.js@10.6.0
├─ entities@6.0.1
├─ html-encoding-sniffer@4.0.0
├─ http-proxy-agent@7.0.2
├─ https-proxy-agent@7.0.6
├─ iconv-lite@0.6.3
├─ is-potential-custom-element-name@1.0.1
├─ jsdom@26.1.0
├─ lru-cache@10.4.3
├─ nwsapi@2.2.21
├─ parse5@7.3.0
├─ safer-buffer@2.1.2
├─ saxes@6.0.0
├─ symbol-tree@3.2.4
├─ tldts-core@6.1.86
├─ tldts@6.1.86
├─ tough-cookie@5.1.2
├─ tr46@5.1.1
├─ w3c-xmlserializer@5.0.0
├─ whatwg-url@14.2.0
├─ ws@8.18.3
└─ xmlchars@2.2.0

Package jsdom installed, re-run the command to start.
error Command failed with exit code 43.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2025-08-03 05:17:12
PS C:\code\MyMultiplicationDrills\multiplicationdrill> Set-Location "C:\code\MyMultiplicationDrills\multiplicationdrill\";  Get-Date -Format "yyyy-MM-dd HH:mm:ss"; yarn;  Get-Date -Format "yyyy-MM-dd HH:mm:ss"; yarn build; Get-Date -Format "yyyy-MM-dd HH:mm:ss"; yarn test; Get-Date -Format "yyyy-MM-dd HH:mm:ss";
2025-08-03 05:17:22
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.49s.
2025-08-03 05:17:23
yarn run v1.22.22
$ tsc && vite build
vite v7.0.6 building for production...
✓ 8 modules transformed.
dist/index.html                 3.05 kB │ gzip: 0.87 kB
dist/assets/index-DP3U4Tpo.css  5.38 kB │ gzip: 1.62 kB
dist/assets/index-DuqwcOGr.js   7.47 kB │ gzip: 2.48 kB │ map: 25.34 kB
✓ built in 435ms
Done in 4.25s.
2025-08-03 05:17:28
yarn run v1.22.22
$ vitest

 DEV  v1.6.1 C:/code/MyMultiplicationDrills/multiplicationdrill

 ✓ src/__tests__/signals.test.ts (9)
 ✓ src/__tests__/utils.test.ts (10)
 ✓ src/__tests__/state.test.ts (9)

 Test Files  3 passed (3)
      Tests  28 passed (28)
   Start at  05:17:30
   Duration  22.41s (transform 517ms, setup 1ms, collect 828ms, tests 69ms, environment 58.62s, prepare 5.55s)

 PASS  Waiting for file changes...
       press h to show help, press q to quit
Done in 39.40s.
2025-08-03 05:18:08
PS C:\code\MyMultiplicationDrills\multiplicationdrill>